baseURL = "https://example.edu"
languageCode = "en-us"
title = "Toby Nowacki"
theme = "avicenna"
googleAnalytics = "UA-1234-6"
timeout=3000

[params]
  subtitle= "PhD Student"
  interests="Comparative Political Institutions, Strategic Voting, Political Methodology "
  cv_name= "HadiSinaee_CV.pdf"
  blog="http://myblog.edu"

[[params.affilation]]
  name = "Dept. of Political Science, Stanford University"
  position = "PhD Student"
  contact = "tnowacki@stanford.edu"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/tobiasnowacki"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/tobiasnowacki"


[[params.introduction.paragraph]]
  text="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
	 Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi. Integer feugiat scelerisque varius morbi enim.
	  A diam maecenas sed enim ut sem viverra. Orci eu lobortis elementum nibh tellus.
		Egestas sed sed risus pretium quam vulputate dignissim suspendisse in.
		Accumsan sit amet nulla facilisi morbi tempus iaculis urna. Condimentum lacinia quis vel eros donec.
   """
[[params.introduction.paragraph]]
  text=""" Pellentesque nec nam aliquam sem et tortor consequat id porta.
	Viverra suspendisse potenti nullam ac. Leo vel orci porta non pulvinar neque laoreet.
	Nulla facilisi nullam vehicula ipsum a arcu. Tempus egestas sed sed risus pretium quam vulputate dignissim suspendisse.
	Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Dui sapien eget mi proin sed libero.
	Quam pellentesque nec nam aliquam sem et tortor consequat id. Aliquet lectus proin nibh nisl.
  """


[[params.projects]]
	[[params.projects.project]]
		name = "Strategic Voting in Plurality and IRV"
		description  = "Enim facilisis gravida neque convallis a. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse.Velit egestas dui id ornare arcu odio ut sem. Nec nam aliquam sem et tortor. In nisl nisi scelerisque eu ultrices vitae auctor."
		project_page = "https://myprojecthomepage.com"
		code_link = "https://github.com/tobiasnowacki/strategicvoting"
		blog_link = "https://ablogpost.com"

 [[params.projects.project]]
		name = "Electoral Vulnerability and Parliamentary Dissent"
		description  = ""
		project_page = "https://myprojecthomepage.com"
		code_link = "https://github.com/tobiasnowacki/vulnerability"
		blog_link = ""

